In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5,6,6]
sum(x)

27

In [3]:
print(x)

[1, 2, 3, 4, 5, 6, 6]


In [ ]:
# ndarray - n dimensional array 

In [4]:
nx = np.array([1,2,3,4,5,6])
print(nx)

[1 2 3 4 5 6]


In [6]:
print(type(nx))

<class 'numpy.ndarray'>


In [7]:
nx.sum()#its a method

21

In [9]:
nx.shape#its a property 

(6,)

In [10]:
nz = np.array(
    [[1,2,3],[3,4,5],[6,7,8]]
)

In [11]:
nz.shape

(3, 3)

In [12]:
print(nz)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [14]:
a = np.array(
    [
        [[1,2,3],[2,3,4],[5,6,7]],
        [[6,7,8],[2,3,1],[3,2,1]]
    ]
)
print(a)
print('---')
print(a.shape)

[[[1 2 3]
  [2 3 4]
  [5 6 7]]

 [[6 7 8]
  [2 3 1]
  [3 2 1]]]
---
(2, 3, 3)


In [15]:
x= np.zeros((5,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
x= np.zeros((5,5),dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [17]:
x = np.ones((5,5,),dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
x = np.full((2,18),101)
print(x)

[[101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101]
 [101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101]]


for sequence generation , we have to function
- arange
- linsapace
- longspace

In [19]:
np.arange(-1,1,.1)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [20]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [21]:
np.arange(1,17).reshape(4,4)
print(x)

[[101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101]
 [101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101]]


In [24]:
np.arange(1,17).reshape(2,2,2,2)
print(x)

[[101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101]
 [101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101]]


In [25]:
x = np.linspace(-np.pi,np.pi, 15)
print(x)

[-3.14159265 -2.6927937  -2.24399475 -1.7951958  -1.34639685 -0.8975979
 -0.44879895  0.          0.44879895  0.8975979   1.34639685  1.7951958
  2.24399475  2.6927937   3.14159265]


In [26]:
x = np.logspace(1,100,20)
print(x)

[1.00000000e+001 1.62377674e+006 2.63665090e+011 4.28133240e+016
 6.95192796e+021 1.12883789e+027 1.83298071e+032 2.97635144e+037
 4.83293024e+042 7.84759970e+047 1.27427499e+053 2.06913808e+058
 3.35981829e+063 5.45559478e+068 8.85866790e+073 1.43844989e+079
 2.33572147e+084 3.79269019e+089 6.15848211e+094 1.00000000e+100]


In [27]:
import matplotlib.pyplot as plt

In [28]:
plt.plot(x)

In [32]:
x = np.arange(-3*np.pi,3*np.pi,0.5)
y = np.sin(x)
z = np.cos(x)
plt.plot(x,y, 'ro--')
plt.plot(x,z, 'bx--')


slicing
*syntax*
- x[start:end:step]
- x[rowstart: rowend: rowstep, colstart: colend:colstep]

In [34]:
x = np.random.randint(11,20,(5,6))
print(x)

[[19 11 19 16 12 13]
 [12 14 17 16 17 15]
 [18 11 18 17 16 12]
 [11 13 15 16 18 15]
 [17 12 15 13 12 18]]


In [36]:
x[0] # first row

array([19, 11, 19, 16, 12, 13])

In [38]:
x[-1] # last row

array([17, 12, 15, 13, 12, 18])

In [39]:
x.sum()

448

In [40]:
x[:, 0] # first column

array([19, 12, 18, 11, 17])

In [41]:
x[:, -1] # last column

array([13, 15, 12, 15, 18])

In [42]:
x[1:4, 1:4] # rows 1 to 3, columns 1 to 3

array([[14, 17, 16],
       [11, 18, 17],
       [13, 15, 16]])