In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
print(type(arr))
#type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

1.21.5


In [5]:
#Use a tuple to create a NumPy array
arr= np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# Dimensions in Arrays
- A dimension in arrays is one level of array depth (nested arrays).
#nested array: are arrays that have arrays as their elements.

In [6]:
#0-D Arrays
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr = np.array(42)
print(arr)

42


In [7]:
#1-D Arrays
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
#2-D Arrays
#An array that has 1-D arrays as its elements is called a 2-D array.

#These are often used to represent matrix or 2nd order tensors.

####NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.

#These are often used to represent a 3rd order tensor.

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,2,1]]])
print(arr)
type(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 2 1]]]


numpy.ndarray

# Check Number of Dimensions
- numpy array provides us ndim attribute that returns an integer that tells us that how many dimennsions the array have

In [4]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

#An array can have any number of dimensions.
- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [9]:
# Create an array with 5 dimensions and verify that it has 5 dimensions
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("dimension of array is:", arr.ndim)
#In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector,
#  the 3rd dim has 1 element that is the matrix with the vector, 
# the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array

[[[[[1 2 3 4]]]]]
dimension of array is: 5


# NumPy Array Indexing
- Access Array Elements
You can access an array element by referring to its index number.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [12]:
#Get the first element from the following array
arr = np.array([5,4,3,2,1])
print(arr[0])
#Get the second element from the following array.
print(arr[1])

#Get third and fourth elements from the following array and add them
print(arr[2] + arr[3])

5
4
5


# Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [13]:
#Access the element on the first row, second column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('second element on first row', arr[0,1])

second element on first row 2


In [14]:
#Access the element on the 2nd row, 5th column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('fifth element on second row', arr[1,4])

fifth element on second row 10


# Access 3-D Arrays

In [17]:
#Access the third element of the second array of the first array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('third element of second array of first array',arr[0,1,2])
"""arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6"""

third element of second array of first array 6


'arr[0, 1, 2] prints the value 6.\n\nAnd this is why:\n\nThe first number represents the first dimension, which contains two arrays:\n[[1, 2, 3], [4, 5, 6]]\nand:\n[[7, 8, 9], [10, 11, 12]]\nSince we selected 0, we are left with the first array:\n[[1, 2, 3], [4, 5, 6]]\n\nThe second number represents the second dimension, which also contains two arrays:\n[1, 2, 3]\nand:\n[4, 5, 6]\nSince we selected 1, we are left with the second array:\n[4, 5, 6]\n\nThe third number represents the third dimension, which contains three values:\n4\n5\n6\nSince we selected 2, we end up with the third value:\n6'

# Negative Indexing
Use negative indexing to access an array from the end.

In [18]:
#Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('last element of second dim', arr[1,-1])

last element of second dim 10


# NumPy Array Slicing
- Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [19]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [20]:
#Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])


[5 6 7]


In [21]:
#Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


# Negative Slicing
Use the minus operator to refer to an index from the end:

In [22]:
#Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


# STEP
Use the step value to determine the step of the slicing:

In [23]:
#Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [24]:
#Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


# Slicing 2-D Arrays

In [25]:
#From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) #Remember that second element has index 1.
print(arr[1, 1:4])


[7 8 9]


In [28]:
#From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [29]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Data Types in Python
By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

  -  i - integer
  -  b - boolean
  -  u - unsigned integer
  -  f - float
  -  c - complex float
  -  m - timedelta
  -  M - datetime
  -  O - object
  -  S - string
  -  U - unicode string
  -  V - fixed chunk of memory for other type ( void )

# Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [30]:
#Get the data type of an array object:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [31]:
#Get the data type of an array containing strings:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [34]:
# Create an array with data type string
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [38]:
# Create an array with data type 4 bytes integer:
arr = np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


# Converting Data Type on Existing Arrays
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [4]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [5]:
# Change data type from float to integer by using int as parameter value
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [6]:
# Change data type from integer to boolean:
arr = np.array([1, 0, 3])
newarr = arr.astype('bool')
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View

- The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# copy

In [7]:
#Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 40
print(arr)
print(x)
#The copy SHOULD NOT be affected by the changes made to the original array.

[40  2  3  4  5]
[1 2 3 4 5]


# view

In [10]:
# make a view ,chnage the original array and and display both arrays
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 30
print(arr)
print(x)
#The view SHOULD be affected by the changes made to the original array.

[30  2  3  4  5]
[30  2  3  4  5]


# Make Changes in the VIEW:

In [11]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)


[31  2  3  4  5]
[31  2  3  4  5]


# Check if Array Owns its Data

 copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute ''base'' that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.



In [12]:
# Print the value of the base attribute to check if an array owns it's data or not:
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)



None
[1 2 3 4 5]


# NumPy Array Shape

The shape of an array is the number of elements in each dimension.

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [13]:
# Print the shape of a 2-D array:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)


(2, 4)


In [16]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('shape of araay', arr.shape)

[[[[[1 2 3 4]]]]]
shape of araay (1, 1, 1, 1, 4)


# NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

# Reshape From 1-D to 2-D

In [17]:
# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

In [18]:
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Returns Copy or View?

In [2]:
# check if return array is copy or view
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = (arr.reshape(2,4).base)
print(newarr)


[1 2 3 4 5 6 7 8]


Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [5]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [6]:
# Convert the array into a 1D array:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [7]:
# Iterate on the elements of the following 1-D array:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [8]:
# In a 2-D array it will go through all the rows.
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)


[1 2 3]
[4 5 6]


If we iterate on a n-D array it will go through n-1th dimension one by one.

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [9]:
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)


1
2
3
4
5
6


In [10]:
# Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [12]:
# Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [13]:
# Iterate through the following 3-D array:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [14]:
# Iterate through the array as a string:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [15]:
# Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [16]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [17]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [19]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]
